name: Node.js CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  test_unit:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit
  test_integration:
    runs-on: ubuntu-latest
    needs: [build, test_unit]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: danylo
          POSTGRES_PASSWORD: root
          POSTGRES_DB: tests
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci && npm install -g dotenv-cli
      - name: Connect to PostgreSQL
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://danylo:root@localhost:5433/tests
      - name: Seed database
        run: npx prisma db seed -- --env test
        env:
          DATABASE_URL: postgresql://danylo:root@localhost:5433/tests
      - name: Run integration tests
        run: npm run test:integration
        env:
          DATABASE_URL: postgresql://danylo:root@localhost:5433/tests
  test_e2e:
    runs-on: ubuntu-latest
    needs: [build, test_unit]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: danylo
          POSTGRES_PASSWORD: root
          POSTGRES_DB: tests
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci && npm install -g dotenv-cli
      - name: Connect to PostgreSQL
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://danylo:root@localhost:5433/tests
      - name: Seed database
        run: npx prisma db seed -- --env test
        env:
          DATABASE_URL: postgresql://danylo:root@localhost:5433/tests
      - name: Run integration tests
        run: npm run start && npm run test:e2e
        env:
          JWT_SECRET: ${{ env.JWT_SECRET }}
          DATABASE_URL: postgresql://danylo:root@localhost:5433/tests        


